### ISSUE TITLE
I've used and prefer the gorilla RPC package

### ISSUE THREAD

**Issue by bakins** [kelseyhightower/jsonrpc-server#1]
http://davebehnke.com/gorilla-go-json-rpc.html
Used in several projects and "plays nice" with middleware, etc.
(Issue was quickest was to comment...)

**Comment by bakins** [comment]
Inspired by this, I hacked this up this morning: https://github.com/bakins/json-rpc-example

**Comment by kelseyhightower** [comment]
@bakins Yeah, it is pretty nice. I did this so I can stick with the standard lib for simple projects.

**Comment by bakins** [comment]
If only I had simple projects :) thanks for the example. TBH, I found the gorilla stuff more straight forward and I wind up using other parts of it anyway.
